//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qua2ma {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qua2ma.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert a directory of qps.
        /// </summary>
        internal static string Example_ConvertQpDir {
            get {
                return ResourceManager.GetString("Example_ConvertQpDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert single qp.
        /// </summary>
        internal static string Example_ConvertSingleQp {
            get {
                return ResourceManager.GetString("Example_ConvertSingleQp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert file to directory.
        /// </summary>
        internal static string Example_ConvertToDirectory {
            get {
                return ResourceManager.GetString("Example_ConvertToDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Example_Language {
            get {
                return ResourceManager.GetString("Example_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert qua &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Fail_Convert_Qua {
            get {
                return ResourceManager.GetString("Fail_Convert_Qua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert qp &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Fail_ConvertQp {
            get {
                return ResourceManager.GetString("Fail_ConvertQp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is not valid..
        /// </summary>
        internal static string Fail_InvalidPath {
            get {
                return ResourceManager.GetString("Fail_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already exists. Overwrite? (Y/[N]).
        /// </summary>
        internal static string FileExists_AskOverwrite {
            get {
                return ResourceManager.GetString("FileExists_AskOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped conversion of &apos;{0}&apos; since output file &apos;{1}&apos; already exists.
        /// </summary>
        internal static string Skip_FileExists {
            get {
                return ResourceManager.GetString("Skip_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully converted &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string Success_ConvertQp {
            get {
                return ResourceManager.GetString("Success_ConvertQp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted &apos;{0}&apos; to &apos;{1}&apos; with {2} maps failing to convert.
        /// </summary>
        internal static string Success_SomeFailed {
            get {
                return ResourceManager.GetString("Success_SomeFailed", resourceCulture);
            }
        }
    }
}
